### ISSUE TITLE
Use of project_apps

### ISSUE THREAD

**Issue by tsloughter** [efene/rebar3_efene_compile#1]
You shouldn't use `rebar_state:project_apps/1` to do compilation. This will  make the plugin unusable when used by a dependency. `project_apps` should only be used by a plugin that is meant to always be run at the top level -- like `rebar3 run`.

Maybe look at the neotoma plugin, using `rebar_state:dir/1` is the way to go https://github.com/tsloughter/rebar3_neotoma_plugin/blob/master/src/rebar3_neotoma_plugin.erl#L41

**Comment by marianoguerra** [comment]
seems to work, reopen if you think I did it wrong, thanks for the report
